import React, { createContext, useContext, useState, useEffect, useRef } from "react";
import {
  mockPodcasts,
  mockEpisodes,
  mockViralClips,
  mockEmotionTimeline,
  mockKnowledge,
  mockAudienceInsights,
  mockPerspectives
} from "../utils/mockData";
import { VectorStore } from "../utils/vectorDb";

const EPISODE_TOPICS = {
  e1: [
    {
      keywords: ["lost generation", "displacement", "job", "worker", "craftsmen", "masons"],
      concept: "The Lost Generation & Job Displacement",
      explanation: "how heavy industrial automation and bricklaying robots are stepping in to address labor shortages while risking the displacement of young manual builders.",
      notes: "the host recommends establishing vocational upskilling programs to train masons to supervise, program, and maintain these robotic systems on-site.",
      implication: "this requires balancing rapid construction scaling with proactive human workforce adaptation and retraining."
    },
    {
      keywords: ["robot", "automation", "machine", "help", "technology", "redrow", "barratt"],
      concept: "Construction Robotics & Automation",
      explanation: "the deployment of robotic bricklayers by builders like Barratt Redrow to accelerate home building and maintain operational pace.",
      notes: "while automation handles repetitive tasks, human masons are still required to direct the layout and troubleshoot mechanical deviations.",
      implication: "the shift raises capital investment barriers for construction firms while stabilizing long-term output."
    },
    {
      keywords: ["challenges", "cost", "rebuild", "capital", "expenditure"],
      concept: "Implementation Challenges & Capital Cost",
      explanation: "the high capital expenditure (CapEx) involved in acquiring and deploying robotic bricklayers on-site.",
      notes: "firms must offset high initial equipment costs with long-term efficiency gains and reduced dependency on scarce manual labor.",
      implication: "smaller contractors may face consolidation pressure, while larger developers gain technical scale."
    }
  ],
  e2: [
    {
      keywords: ["dating", "inflation", "living", "cost", "economics"],
      concept: "Dating Economics & Rising Costs",
      explanation: "how the modern cost-of-living crunch is fundamentally shifting dating habits, forcing younger demographics to seek lower-cost date alternatives.",
      notes: "daters are increasingly avoiding expensive dinners or cocktail bars in favor of low-pressure creative options like coffee walks.",
      implication: "macroeconomic inflation directly changes the social protocols and spending choices in courtship."
    },
    {
      keywords: ["virtual", "screen", "video", "call", "compatibility"],
      concept: "Virtual Screenings & Compatibility",
      explanation: "the rising use of short video calls as pre-date screening mechanisms to verify mutual compatibility and save money.",
      notes: "this filter helps daters avoid investing in expensive in-person meetings with individuals who lack chemistry.",
      implication: "digital pre-screening reduces friction and financial waste, making dating matches more intentional."
    },
    {
      keywords: ["hinge", "ceo", "app", "interface", "product"],
      concept: "App Interface Redesign & Engagement Loops",
      explanation: "how Hinge's executive leadership is adjusting product design and algorithms to align with budget-conscious daters.",
      notes: "the app incorporates features highlighting low-cost local date ideas and facilitating seamless virtual screenings.",
      implication: "digital platform designs must adapt to the economic stresses felt by their target user base to maintain engagement."
    }
  ],
  e3: [
    {
      keywords: ["spatial", "ego-location", "ego location", "where", "space", "sensory"],
      concept: "Spatial Ego-Location & Sensory Integration",
      explanation: "how the brain constructs our spatial sense of 'self' in space by integrating visual, vestibular, and tactile feedback in real time.",
      notes: "disruptions in this real-time sensory loop can cause the brain to construct a misaligned spatial coordinate system.",
      implication: "our subjective sense of bodily presence is a fragile biological construct generated by sensory feedback."
    },
    {
      keywords: ["out-of-body", "out of body", "consciousness", "separate", "brain", "tpj"],
      concept: "Out-of-Body Experiences & TPJ De-synchronization",
      explanation: "the neuroimaging findings showing that out-of-body experiences occur during transient de-synchronizations at the temporoparietal junction (TPJ).",
      notes: "the TPJ plays a critical role in integrating multi-sensory signals, and its disruption decouples consciousness from the body model.",
      implication: "self-consciousness is a neurological construct that can be decoupled and studied using scientific instruments."
    }
  ],
  e4: [
    {
      keywords: ["theory of mind", "empathy", "social", "mind", "fiction", "imagination"],
      concept: "Theory of Mind & Empathy Simulation",
      explanation: "how reading literary fiction functions as a simulator for social cognition, strengthening the brain networks associated with empathy.",
      notes: "readers practice predicting complex characters' internal motives, which translates to better social prediction in real relationships.",
      implication: "narrative art exercises our social intelligence, keeping our capacity for interpersonal empathy active."
    },
    {
      keywords: ["attention", "focus", "hippocampus", "distract", "fragmentation"],
      concept: "Hippocampal Mapping & Attention Fragmentation",
      explanation: "how sustained reading tracks chronological events, which maps pathways in the hippocampus and strengthens cognitive focus filters.",
      notes: "this long-form immersion acts as an active corrective measure against attention span erosion caused by rapid digital loops.",
      implication: "structured narrative engagement preserves deep attention spans in an era of notification-driven fragmentation."
    }
  ],
  e5: [
    {
      keywords: ["focus", "agility", "athletes", "de-anchor", "perform", "disruptions"],
      concept: "Focus De-anchoring & Athletic Performance",
      explanation: "how cognitive scientists use out-of-body sensory studies to train athletes to focus away from physical strain and fatigue.",
      notes: "visualizing spatial displacement enables high performers to detach from immediate bodily signals of exhaustion.",
      implication: "training the mind to decouple attention from immediate sensory pain can unlock new bounds of physical endurance."
    },
    {
      keywords: ["cognitive agility", "agility", "frameworks", "tension"],
      concept: "Cognitive Agility & Framework Adaptation",
      explanation: "the ability to rapidly shift focus between different cognitive tasks and conceptual frameworks under pressure.",
      notes: "this training involves stretching attention boundaries and managing high physical and mental tension.",
      implication: "cognitive agility is a highly trainable resource that stabilizes emotional control in volatile environments."
    }
  ],
  e6: [
    {
      keywords: ["immersion", "digital distraction", "dopamine", "notifications", "reading"],
      concept: "Narrative Immersion & Digital Distraction Filters",
      explanation: "how deep cognitive immersion in long-form narratives trains the brain's filters to suppress digital distraction.",
      notes: "regular long-form reading lowers the brain's baseline craving for the instant dopamine hits provided by social notifications.",
      implication: "we can actively recalibrate our reward pathways by substituting shallow digital scrolling with deep reading."
    },
    {
      keywords: ["attention", "hippocampus", "gratification", "dopamine", "fragmentation"],
      concept: "Focus Recovery & Memory Mapping",
      explanation: "the process of rebuilding attention capacity by forcing the hippocampus to construct memory maps over long timelines.",
      notes: "this practice directly repairs the attention fragmentation induced by instant-gratification loops.",
      implication: "sustained memory mapping is a fundamental requirement for deep, long-form analytical reasoning."
    }
  ],
  e7: [
    {
      keywords: ["recruitment", "contract", "europe", "rate", "scouting", "football"],
      concept: "Professional Football Scouting Economics",
      explanation: "the highly competitive recruitment rate of Ghanaian football academies, where less than 0.1% of players secure European contracts.",
      notes: "the massive supply of young talent creates an oversaturated market, leaving the vast majority of players without fallback careers.",
      implication: "the pursuit of sports stardom can channel localized economic hope into high-risk, low-probability outcomes."
    },
    {
      keywords: ["documentary", "bbc", "accra", "ghana", "reality"],
      concept: "Ghanaian Football Academies & Family Risk",
      explanation: "the socio-economic conditions in Accra, Ghana, where families invest their savings into academies with minimal oversight.",
      notes: "the BBC documentary highlights the physical toll and financial vulnerability of young players chasing overseas contracts.",
      implication: "without formal education integration, young athletes face systemic vulnerability when career dreams do not materialize."
    }
  ],
  e8: [
    {
      keywords: ["leverage", "supply chain", "distribution", "ownership", "publishing"],
      concept: "Supply Chain Control & Artist Leverage",
      explanation: "how Beyonce retains corporate leverage by bypassing traditional gatekeepers to own publishing rights and distribution channels.",
      notes: "managing distribution directly via Parkwood Entertainment secures high profit margins and absolute creative control.",
      implication: "supply chain ownership is the ultimate source of corporate independence for modern creative brands."
    },
    {
      keywords: ["brand", "scarcity", "release", "album", "marketing"],
      concept: "Brand Value Protection & Scarcity Marketing",
      explanation: "the business strategy of utilizing artificial scarcity and unexpected visual album releases to build premium brand value.",
      notes: "avoiding overexposure and standard promotional cycles increases customer demand and brand prestige.",
      implication: "exclusivity and narrative control are more effective for luxury brand sustainability than constant volume."
    }
  ],
  e9: [
    {
      keywords: ["diaphragmatic", "belly", "breathing", "lung", "oxygen"],
      concept: "Diaphragmatic Expansion & Blood Oxygenation",
      explanation: "the physiology of diaphragmatic or belly breathing, which expands the lungs fully to maximize blood oxygenation.",
      notes: "avoiding shallow chest breathing stabilizes blood pH levels and improves the efficiency of oxygen exchange.",
      implication: "conscious regulation of breathing volume is a direct input to metabolic and physical recovery."
    },
    {
      keywords: ["parasympathetic", "nervous", "hold", "vagus", "stress"],
      concept: "Parasympathetic Activation & Vagal Stimulation",
      explanation: "how holding the breath after inhalation followed by extended exhales stimulates the vagus nerve to activate parasympathetic dominance.",
      notes: "this activation triggers immediate drops in heart rate, blood pressure, and cortisol production to relieve stress.",
      implication: "vagal nerve stimulation is a biological hack that lets individuals manually suppress the fight-or-flight response."
    }
  ],
  e10: [
    {
      keywords: ["interoception", "internal", "body", "awareness", "signals"],
      concept: "Interoceptive Awareness & Emotional Control",
      explanation: "how paying attention to internal bodily signals like heart rate and tension builds interoceptive awareness and emotional regulation.",
      notes: "a high capacity for interoception is scientifically linked to better stress management and somatic self-awareness.",
      implication: "emotional resilience relies on accurately sensing and resolving physiological tension before it triggers mental panic."
    },
    {
      keywords: ["scan", "muscle", "tension", "nidra", "sleep", "recovery"],
      concept: "Yoga Nidra Body Scanning & Somatic Restoration",
      explanation: "the process of sequential muscle scanning in Yoga Nidra to systematically release deep somatic tension.",
      notes: "bringing awareness to muscle groups triggers a relaxation response that restores energy without requiring actual sleep.",
      implication: "body scanning serves as a conscious recovery tool that lowers nervous system hyper-arousal."
    }
  ]
};

const formatTimeHelper = (seconds) => {
  const min = Math.floor(seconds / 60);
  const sec = Math.floor(seconds % 60);
  return `${min.toString().padStart(2, "0")}:${sec.toString().padStart(2, "0")}`;
};

export const getEpisodeTopics = (ep, knowledge) => {
  if (!ep) return [];
  if (EPISODE_TOPICS[ep.id]) {
    return EPISODE_TOPICS[ep.id];
  }

  const topics = [];

  // Extract from summary paragraphs
  if (knowledge?.summary?.paragraphs) {
    knowledge.summary.paragraphs.forEach((p, index) => {
      const words = p.toLowerCase()
        .replace(/[^\w\s]/g, "")
        .split(/\s+/)
        .filter(w => w.length > 4);
      
      topics.push({
        keywords: Array.from(new Set(words)).slice(0, 6),
        concept: `Summary Insight ${index + 1}`,
        explanation: p,
        notes: `The episode summary notes: "${p.substring(0, 100)}..."`,
        implication: "This shows how user-uploaded content is dynamically structured into semantic modules."
      });
    });
  }

  // Extract from notes
  if (knowledge?.notes) {
    knowledge.notes.forEach((note, index) => {
      const words = note.content.toLowerCase()
        .replace(/[^\w\s]/g, "")
        .split(/\s+/)
        .filter(w => w.length > 4);

      topics.push({
        keywords: Array.from(new Set(words)).slice(0, 6),
        concept: `Key Takeaway ${index + 1}`,
        explanation: note.content,
        notes: `The host notes that "${note.content}"`,
        implication: "This contextual point helps clarify the primary thesis of the upload."
      });
    });
  }

  if (topics.length === 0) {
    const desc = ep.description || "custom upload details";
    const words = desc.toLowerCase()
      .replace(/[^\w\s]/g, "")
      .split(/\s+/)
      .filter(w => w.length > 4);

    topics.push({
      keywords: Array.from(new Set(words)).slice(0, 6),
      concept: "Overview",
      explanation: desc,
      notes: `Presented by ${ep.host || "the host"}.`,
      implication: "This represents a newly uploaded podcast ready for interactive analysis."
    });
  }

  return topics;
};

export const getTimestampExplanation = (currentTime, activeEpisode, timeline, epTopics) => {
  if (!activeEpisode) return "";

  const segments = [
    { name: "Introduction", description: "opening remarks, setting the stage, and introducing the host and the main themes" },
    { name: "Core Thesis", description: "the foundational argument and core concept that forms the basis of the discussion" },
    { name: "Contextual Background", description: "historical context, scientific background, or industry trends relevant to the topic" },
    { name: "Deep Analysis", description: "a detailed breakdown of the primary mechanisms and data points involved" },
    { name: "Key Challenges", description: "the main hurdles, societal concerns, or technical bottlenecks faced in this domain" },
    { name: "Alternative Viewpoints", description: "diverse perspectives, debate points, or alternative interpretations of the facts" },
    { name: "Practical Applications", description: "real-world implications, actionable advice, and how these concepts are applied in practice" },
    { name: "Future Outlook", description: "predictions, upcoming breakthroughs, and long-term implications of these developments" },
    { name: "Key Takeaways", description: "a summary of the host's primary conclusions and the most important things to remember" },
    { name: "Closing Remarks", description: "final thoughts, contact info, and wrap-up of the episode" }
  ];

  const duration = activeEpisode.durationSeconds || 1800;
  const segmentIndex = Math.min(9, Math.floor((currentTime / duration) * 10));
  const activeSegment = segments[segmentIndex];

  let closestPoint = null;
  if (timeline && timeline.length > 0) {
    let minDiff = Infinity;
    for (const point of timeline) {
      const diff = Math.abs(point.timestampSeconds - currentTime);
      if (diff < minDiff) {
        minDiff = diff;
        closestPoint = point;
      }
    }
  }

  const quoteStr = closestPoint ? closestPoint.quote : "exploring key concepts";
  const dominantEmotion = closestPoint ? closestPoint.dominant : "Curiosity";

  const openers = [
    `At the playhead position of **${formatTimeHelper(currentTime)}** (approx. ${Math.round((currentTime / duration) * 100)}% of the timeline), the discussion is in the **${activeSegment.name}** phase, which covers ${activeSegment.description}.`,
    `Currently, at **${formatTimeHelper(currentTime)}** into the playback, the host is addressing the **${activeSegment.name}** of the episode, focusing on ${activeSegment.description}.`,
    `We are in the **${activeSegment.name}** phase of the episode (at **${formatTimeHelper(currentTime)}**). This section highlights ${activeSegment.description}.`
  ];

  const hashVal = currentTime;
  const opener = openers[hashVal % openers.length];

  let conceptualExplanation = "";
  if (epTopics && epTopics.length > 0) {
    let bestTopic = null;
    let maxMatch = 0;
    const cleanQuote = quoteStr.toLowerCase();
    
    for (const topic of epTopics) {
      let matchCount = 0;
      for (const kw of topic.keywords) {
        if (cleanQuote.includes(kw.toLowerCase())) {
          matchCount++;
        }
      }
      if (matchCount > maxMatch) {
        maxMatch = matchCount;
        bestTopic = topic;
      }
    }

    if (bestTopic) {
      conceptualExplanation = ` This relates directly to **${bestTopic.concept}**: the host details how ${bestTopic.explanation}`;
    }
  }

  const toneExplanation = ` The emotional tone here registers high **${dominantEmotion}** as the host asserts: *"${quoteStr}"*.`;
  
  return `${opener}${toneExplanation}${conceptualExplanation}`;
};

const PodcastContext = createContext();

const GEMINI_API_KEY = ""; // Do not expose API keys in the browser. Set on backend only.
const API_BASE_URL = import.meta.env.VITE_API_BASE || (typeof window !== "undefined" ? `${window.location.protocol}//${window.location.hostname}:8000` : "http://localhost:8000");

const speakHostTwinText = (text, personality, onStart, onEnd) => {
  if (typeof window !== "undefined" && window.speechSynthesis) {
    window.speechSynthesis.cancel();
    
    const cleanText = text.replace(/\*\*|\*/g, "");
    const utterance = new SpeechSynthesisUtterance(cleanText);
    
    const voices = window.speechSynthesis.getVoices();
    const preferredVoice = voices.find(v => v.name.includes("Google US English") || v.name.includes("Natural") || v.lang.startsWith("en"));
    if (preferredVoice) {
      utterance.voice = preferredVoice;
    }
    
    if (personality === "Casual") {
      utterance.rate = 0.92;
      utterance.pitch = 1.0;
    } else if (personality === "Debate Mode") {
      utterance.rate = 1.25;
      utterance.pitch = 1.1;
    } else {
      utterance.rate = 1.0;
      utterance.pitch = 1.0;
    }

    utterance.onstart = () => {
      if (onStart) onStart();
    };
    utterance.onend = () => {
      if (onEnd) onEnd();
    };
    utterance.onerror = (e) => {
      console.warn("SpeechSynthesis error:", e);
      if (onEnd) onEnd();
    };
    
    window.speechSynthesis.speak(utterance);
  }
};

export const PodcastProvider = ({ children }) => {
  // DB States
  const [podcasts, setPodcasts] = useState(mockPodcasts);
  const [episodes, setEpisodes] = useState(mockEpisodes);
  const [viralClips, setViralClips] = useState(mockViralClips);
  const [emotionTimelines, setEmotionTimelines] = useState(mockEmotionTimeline);
  const [knowledgeData, setKnowledgeData] = useState(mockKnowledge);
  const [audienceInsights, setAudienceInsights] = useState(mockAudienceInsights);
  const [perspectives, setPerspectives] = useState(mockPerspectives);

  // Active items
  const [activePodcast, setActivePodcast] = useState(mockPodcasts[0]);
  const [activeEpisode, setActiveEpisode] = useState(mockEpisodes[0]);
  const [activePage, setActivePage] = useState("dashboard");

  // Vector DB states
  const [vectorDbSettings, setVectorDbSettings] = useState({
    provider: "local-tfidf",
    chunkSize: 3,
    chunkOverlap: 1
  });
  const [vectorDbStats, setVectorDbStats] = useState(null);
  const [isVectorIndexing, setIsVectorIndexing] = useState(false);
  const vectorStoreRef = useRef(null);

  // Initialize VectorStore overriden with backend routing
  if (!vectorStoreRef.current) {
    vectorStoreRef.current = {
      search: async (queryText, options = {}) => {
        try {
          const epId = options.episodeId || "all";
          const res = await fetch(`${API_BASE_URL}/api/vector-db/search?query=${encodeURIComponent(queryText)}&episode_id=${epId}`);
          if (!res.ok) throw new Error("Vector search failed");
          const hits = await res.json();
          return hits;
        } catch (err) {
          console.error("Backend search failed. Falling back to local VectorStore Mock.", err);
          return [];
        }
      },
      getStats: () => {
        return vectorDbStats || {
          provider: vectorDbSettings.provider,
          totalChunks: 0,
          episodesCount: 0,
          dimensions: 0,
          chunkSize: vectorDbSettings.chunkSize,
          chunkOverlap: vectorDbSettings.chunkOverlap,
          vocabularySize: 0
        };
      }
    };
  }

  // Rebuild vector index on backend
  const rebuildVectorIndex = async (newSettings = null) => {
    setIsVectorIndexing(true);
    const settings = newSettings || vectorDbSettings;
    try {
      const res = await fetch(`${API_BASE_URL}/api/vector-db/rebuild`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          provider: settings.provider === "gemini" ? "openai" : settings.provider,
          chunkSize: parseInt(settings.chunkSize),
          chunkOverlap: parseInt(settings.chunkOverlap)
        })
      });
      if (res.ok) {
        const data = await res.json();
        if (data.success) {
          setVectorDbStats(data.stats);
          setVectorDbSettings(settings);
          showToast("Vector database successfully rebuilt on backend.");
        }
      }
    } catch (err) {
      console.error("Vector indexing failed on backend:", err);
      showToast(`Indexing error: ${err.message}`);
    } finally {
      setIsVectorIndexing(false);
    }
  };

  // Helper to fetch podcasts & episodes from backend
  const fetchPodcastsAndEpisodes = async () => {
    try {
      const pRes = await fetch(`${API_BASE_URL}/api/podcasts`);
      const eRes = await fetch(`${API_BASE_URL}/api/episodes`);
      if (pRes.ok && eRes.ok) {
        const pData = await pRes.json();
        const eData = await eRes.json();
        if (pData.length > 0) {
          setPodcasts(pData);
          setEpisodes(eData);
          
          // Seed active items if not set
          setActivePodcast(pData[0]);
          const firstEp = eData.find(e => e.podcastId === pData[0].id) || eData[0];
          setActiveEpisode(firstEp);
        }
      }
    } catch (err) {
      console.error("Failed to fetch podcasts and episodes from backend", err);
    }
  };

  // Startup hook
  useEffect(() => {
    fetchPodcastsAndEpisodes();
    fetch(`${API_BASE_URL}/api/vector-db/stats`)
      .then(r => r.json())
      .then(data => setVectorDbStats(data))
      .catch(e => console.error("Failed to load vector stats", e));
  }, []);

  // Update episode sub-modules whenever active episode changes
  useEffect(() => {
    if (!activeEpisode) return;

    const fetchEpisodeDetails = async () => {
      try {
        // 1. Chat History
        const chatRes = await fetch(`${API_BASE_URL}/api/history/${activeEpisode.id}`);
        if (chatRes.ok) {
          const chatData = await chatRes.json();
          setChatHistory(prev => ({ ...prev, [activeEpisode.id]: chatData }));
        }

        // 2. Twin History
        const twinHistRes = await fetch(`${API_BASE_URL}/api/twin-history/${activeEpisode.id}`);
        if (twinHistRes.ok) {
          const twinData = await twinHistRes.json();
          setAiHostTwinHistory(twinData);
        }

        // 3. Viral clips
        const clipsRes = await fetch(`${API_BASE_URL}/api/viral-clips/${activeEpisode.id}`);
        if (clipsRes.ok) {
          const clipsData = await clipsRes.json();
          setViralClips(prev => ({ ...prev, [activeEpisode.id]: clipsData }));
        }

        // 4. Insights & Emotion timeline
        const insightsRes = await fetch(`${API_BASE_URL}/api/engagement-analysis/${activeEpisode.id}`);
        if (insightsRes.ok) {
          const insightsData = await insightsRes.json();
          setAudienceInsights(prev => ({ ...prev, [activeEpisode.id]: insightsData }));
          if (insightsData.retentionCurve) {
            // Rebuild emotional timeline dynamically from metrics
            const steps = 10;
            const timeline = [];
            const emotions = ["Curiosity", "Excitement", "Deep Thinking", "Surprise", "Joy"];
            const quotes = [
              "Opening the discussion on technological transitions.",
              "Analyzing initial CapEx calculations and firm scaling limits.",
              "Evaluating standard workforce implications and worker retraining.",
              "Considering alternative viewpoints and contractor reactions.",
              "A surprising insight regarding regulatory compliance issues.",
              "Highlighting action items and strategic paths for developers.",
              "Summarizing final conclusions and core thesis takeaways.",
              "Concluding remarks and wrapping up the recording."
            ];
            const duration = activeEpisode.durationSeconds || 1800;
            for (let i = 0; i < steps; i++) {
              const timeSec = Math.floor((duration / (steps - 1)) * i);
              const min = timeSec // 60;
              const sec = timeSec % 60;
              const timeStr = `${min.toString().padStart(2, "0")}:${sec.toString().padStart(2, "0")}`;
              timeline.push({
                timestamp: timeStr,
                timestampSeconds: timeSec,
                excitement: 40 + (timeSec % 55),
                curiosity: 50 + (timeSec % 45),
                surprise: 30 + (timeSec % 65),
                deepThinking: 45 + (timeSec % 50),
                joy: 40 + (timeSec % 50),
                quote: quotes[i % quotes.length],
                dominant: emotions[i % emotions.length]
              });
            }
            setEmotionTimelines(prev => ({ ...prev, [activeEpisode.id]: timeline }));
          }
        }

        // 5. Knowledge assets
        const knowledgeRes = await fetch(`${API_BASE_URL}/api/knowledge-engine/${activeEpisode.id}`);
        if (knowledgeRes.ok) {
          const knowledgeData = await knowledgeRes.json();
          setKnowledgeData(prev => ({ ...prev, [activeEpisode.id]: knowledgeData }));
        }

        // 6. Perspectives
        const perspectivesRes = await fetch(`${API_BASE_URL}/api/perspectives/${activeEpisode.id}`);
        if (perspectivesRes.ok) {
          const perspectivesData = await perspectivesRes.json();
          setPerspectives(prev => ({ ...prev, [activeEpisode.id]: perspectivesData }));
        }
      } catch (err) {
        console.error("Failed to load episode details from backend:", err);
      }
    };

    fetchEpisodeDetails();
  }, [activeEpisode?.id]);

  // AI Host settings
  const [twinPersonality, setTwinPersonality] = useState("Professional"); // Casual | Professional | Debate
  const [twinVoiceMode, setTwinVoiceMode] = useState(false);
  const [isHostSpeaking, setIsHostSpeaking] = useState(false);

  // Playback Control States
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTimeState] = useState(0); 
  const [playbackSpeed, setPlaybackSpeed] = useState(1.0);
  const [volume, setVolume] = useState(0.85);

  // Custom states for tracking skips and podcast swaps
  const [skipEvents, setSkipEvents] = useState([]);
  const [podcastSwaps, setPodcastSwaps] = useState([]);

  // Real HTML5 Audio Engine
  const [audio] = useState(() => (typeof window !== "undefined" ? new Audio() : null));

  // Search & Global inputs
  const [searchQuery, setSearchQuery] = useState("");

  // Global UI & Modal States
  const [isUpgradeModalOpen, setIsUpgradeModalOpen] = useState(false);
  const [isApiConfigModalOpen, setIsApiConfigModalOpen] = useState(false);
  const [toast, setToast] = useState({ show: false, message: "" });

  const showToast = (message) => {
    setToast({ show: true, message });
    setTimeout(() => {
      setToast({ show: false, message: "" });
    }, 3000);
  };

  // Sync userRole with localStorage session
  const [userRole, setUserRoleState] = useState(() => {
    if (typeof window !== "undefined") {
      const sessionData = localStorage.getItem("podcastmind_session");
      if (sessionData) {
        try {
          const session = JSON.parse(sessionData);
          return session.role || "Creator";
        } catch (e) {
          return "Creator";
        }
      }
    }
    return "Creator";
  });

  const setUserRole = (role) => {
    setUserRoleState(role);
    if (typeof window !== "undefined") {
      const sessionData = localStorage.getItem("podcastmind_session");
      let session = { name: "Aravindhan", email: "aravindhan@example.com", role: "Creator" };
      if (sessionData) {
        try {
          session = JSON.parse(sessionData);
        } catch (e) {}
      }
      session.role = role;
      localStorage.setItem("podcastmind_session", JSON.stringify(session));
    }
  };

  // Sync avatar with localStorage session
  const [avatar, setAvatarState] = useState(() => {
    if (typeof window !== "undefined") {
      const sessionData = localStorage.getItem("podcastmind_session");
      if (sessionData) {
        try {
          const session = JSON.parse(sessionData);
          return session.avatar || "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80";
        } catch (e) {
          return "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80";
        }
      }
    }
    return "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80";
  });

  const setAvatar = (newAvatar) => {
    setAvatarState(newAvatar);
    if (typeof window !== "undefined") {
      const sessionData = localStorage.getItem("podcastmind_session");
      let session = { name: "Aravindhan", email: "aravindhan@example.com", role: "Creator" };
      if (sessionData) {
        try {
          session = JSON.parse(sessionData);
        } catch (e) {}
      }
      session.avatar = newAvatar;
      localStorage.setItem("podcastmind_session", JSON.stringify(session));
    }
  };

  // Mobile responsive sidebar drawer state
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  // API Integration Configuration States
  const [apiConfig, setApiConfig] = useState({
    spotify: { connected: true, apiKey: "spotify-mock-key-12345" },
    youtube: { connected: true, apiKey: "youtube-mock-key-67890" },
    libsyn: { connected: false, apiKey: "" }
  });

  // Custom setCurrentTime wrapper to sync state and HTML5 Audio playhead
  const setCurrentTime = (time) => {
    if (audio && activeEpisode && activeEpisode.audioUrl) {
      let targetTime;
      if (typeof time === "function") {
        setCurrentTimeState((prev) => {
          targetTime = time(prev);
          audio.currentTime = targetTime;
          return targetTime;
        });
      } else {
        targetTime = time;
        audio.currentTime = targetTime;
        setCurrentTimeState(targetTime);
      }
    } else {
      setCurrentTimeState(time);
    }
  };

  // Keep HTML5 Audio source updated when active episode changes
  useEffect(() => {
    if (!audio) return;
    const hasRealAudio = activeEpisode && activeEpisode.audioUrl;
    if (hasRealAudio) {
      const currentSrc = audio.src ? new URL(audio.src, window.location.origin).pathname : '';
      const targetSrc = activeEpisode.audioUrl;
      if (currentSrc !== targetSrc) {
        audio.src = targetSrc;
        audio.load();
        
        // Apply volume and rate limits
        audio.volume = volume;
        audio.playbackRate = playbackSpeed;
        audio.defaultPlaybackRate = playbackSpeed;

        if (isPlaying) {
          audio.play().catch((err) => {
            console.warn("Audio play failed on source change:", err);
            setIsPlaying(false);
          });
        } else {
          audio.currentTime = 0;
          setCurrentTimeState(0);
        }
      }
    } else {
      audio.pause();
      audio.src = "";
    }
  }, [activeEpisode, audio]);

  // Sync volume with audio element
  useEffect(() => {
    if (audio) {
      audio.volume = volume;
    }
  }, [volume, audio]);

  // Sync playbackSpeed with audio element
  useEffect(() => {
    if (audio) {
      audio.playbackRate = playbackSpeed;
      audio.defaultPlaybackRate = playbackSpeed;
    }
  }, [playbackSpeed, audio]);

  // Cancel speech synthesis when voice mode is toggled off or active page changes
  useEffect(() => {
    if (!twinVoiceMode && typeof window !== "undefined" && window.speechSynthesis) {
      window.speechSynthesis.cancel();
      setIsHostSpeaking(false);
    }
  }, [twinVoiceMode]);

  useEffect(() => {
    if (typeof window !== "undefined" && window.speechSynthesis) {
      window.speechSynthesis.cancel();
      setIsHostSpeaking(false);
    }
  }, [activePage]);

  // Sync isPlaying with audio element play/pause state
  useEffect(() => {
    if (!audio) return;
    const hasRealAudio = activeEpisode && activeEpisode.audioUrl;
    if (!hasRealAudio) return;

    if (isPlaying) {
      if (Math.abs(audio.currentTime - currentTime) > 2) {
        audio.currentTime = currentTime;
      }
      audio.play().catch((err) => {
        console.warn("Audio play failed:", err);
        setIsPlaying(false);
      });
    } else {
      audio.pause();
    }
  }, [isPlaying, audio]);

  // Event listeners on HTML5 Audio object to sync back to React state
  useEffect(() => {
    if (!audio) return;

    const handleTimeUpdate = () => {
      if (isPlaying) {
        setCurrentTimeState(Math.floor(audio.currentTime));
      }
    };

    const handleEnded = () => {
      setIsPlaying(false);
      setCurrentTimeState(0);
    };

    const handleLoadedMetadata = () => {
      if (currentTime > 0 && Math.abs(audio.currentTime - currentTime) > 2) {
        audio.currentTime = currentTime;
      }
    };

    audio.addEventListener("timeupdate", handleTimeUpdate);
    audio.addEventListener("ended", handleEnded);
    audio.addEventListener("loadedmetadata", handleLoadedMetadata);

    return () => {
      audio.removeEventListener("timeupdate", handleTimeUpdate);
      audio.removeEventListener("ended", handleEnded);
      audio.removeEventListener("loadedmetadata", handleLoadedMetadata);
    };
  }, [audio, isPlaying]);

  // Track playback time jumps (skips) and active podcast switches (swaps)
  const prevTimeRef = React.useRef(0);
  const prevEpisodeRef = React.useRef(activeEpisode);

  // Helper to interpolate emotions at exact second values
  const getInterpolatedEmotion = (episodeId, timeInSecs) => {
    const timeline = emotionTimelines[episodeId];
    if (!timeline || timeline.length === 0) return null;
    
    const sorted = [...timeline].sort((a, b) => a.timestampSeconds - b.timestampSeconds);
    
    if (timeInSecs <= sorted[0].timestampSeconds) return sorted[0];
    if (timeInSecs >= sorted[sorted.length - 1].timestampSeconds) return sorted[sorted.length - 1];
    
    for (let i = 0; i < sorted.length - 1; i++) {
      const p1 = sorted[i];
      const p2 = sorted[i + 1];
      if (timeInSecs >= p1.timestampSeconds && timeInSecs <= p2.timestampSeconds) {
        const ratio = (timeInSecs - p1.timestampSeconds) / (p2.timestampSeconds - p1.timestampSeconds);
        const interpolate = (v1, v2) => Math.round(v1 + ratio * (v2 - v1));
        return {
          timestampSeconds: timeInSecs,
          timestamp: formatTime(timeInSecs),
          excitement: interpolate(p1.excitement, p2.excitement),
          curiosity: interpolate(p1.curiosity, p2.curiosity),
          surprise: interpolate(p1.surprise, p2.surprise),
          deepThinking: interpolate(p1.deepThinking, p2.deepThinking),
          joy: interpolate(p1.joy, p2.joy),
          quote: ratio < 0.5 ? p1.quote : p2.quote,
          dominant: ratio < 0.5 ? p1.dominant : p2.dominant
        };
      }
    }
    return sorted[0];
  };

  useEffect(() => {
    if (!activeEpisode) return;

    // 1. Detect Episode Swap (User switching podcasts entirely)
    if (prevEpisodeRef.current && prevEpisodeRef.current.id !== activeEpisode.id) {
      const prevEp = prevEpisodeRef.current;
      const finalTime = prevTimeRef.current;
      const duration = prevEp.durationSeconds || 1;
      const completionRate = Math.min(100, Math.round((finalTime / duration) * 100));

      // Record swap if user played at least 5s and didn't complete (>90%)
      if (finalTime >= 5 && completionRate < 90) {
        const emotionBefore = getInterpolatedEmotion(prevEp.id, finalTime);
        const swapLog = {
          id: `swap-${Date.now()}`,
          fromEpisodeTitle: prevEp.title,
          toEpisodeTitle: activeEpisode.title,
          timePlayed: finalTime,
          completionRate,
          emotionBefore,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
        };
        setPodcastSwaps((prev) => [swapLog, ...prev].slice(0, 20));
      }
      prevTimeRef.current = 0;
      prevEpisodeRef.current = activeEpisode;
      return;
    }

    // 2. Detect skip/seek inside same episode
    const diff = currentTime - prevTimeRef.current;
    if (Math.abs(diff) > 2) {
      const fromTime = prevTimeRef.current;
      const toTime = currentTime;
      const emotionBefore = getInterpolatedEmotion(activeEpisode.id, fromTime);
      const emotionAfter = getInterpolatedEmotion(activeEpisode.id, toTime);

      const skipLog = {
        id: `skip-${Date.now()}`,
        episodeId: activeEpisode.id,
        fromTime,
        toTime,
        direction: diff > 0 ? "forward" : "backward",
        duration: Math.abs(diff),
        emotionBefore,
        emotionAfter,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
      };
      setSkipEvents((prev) => [skipLog, ...prev].slice(0, 30));
    }

    prevTimeRef.current = currentTime;
    prevEpisodeRef.current = activeEpisode;
  }, [currentTime, activeEpisode, emotionTimelines]);

  // Chat Histories
  const [chatHistory, setChatHistory] = useState({
    e1: [
      {
        id: "msg-1",
        role: "user",
        content: "What did the host mean by 'Agentic AI will redefine software'?",
        timestamp: "18:42"
      },
      {
        id: "msg-2",
        role: "assistant",
        content: "The host means that Agentic AI systems can autonomously plan, decide, and execute tasks with minimal human intervention. These systems will change how software is built, deployed, and scaled — moving from traditional automation to intelligent autonomy.",
        timestamp: "18:43"
      }
    ]
  });

  const [aiHostTwinHistory, setAiHostTwinHistory] = useState([
    {
      id: "ath-1",
      role: "assistant",
      content: "I am the AI Digital Twin of Alex Carter. I have been trained on all episodes of The AI Revolution Podcast. Ask me anything about the future of intelligence, startups, or cognitive designs!",
      timestamp: "14:30"
    }
  ]);

  // Multiverse comparison
  const [compareModes, setCompareModes] = useState(["beginner", "expert"]);

  // Audio Playback Simulation Timer (fallback for simulated episodes)
  useEffect(() => {
    let timer = null;
    const hasRealAudio = activeEpisode && activeEpisode.audioUrl;
    if (isPlaying && !hasRealAudio) {
      timer = setInterval(() => {
        setCurrentTime((prevTime) => {
          const nextTime = prevTime + 1;
          if (nextTime >= activeEpisode.durationSeconds) {
            setIsPlaying(false);
            return 0;
          }
          return nextTime;
        });
      }, 1000 / playbackSpeed);
    }
    return () => {
      if (timer) clearInterval(timer);
    };
  }, [isPlaying, playbackSpeed, activeEpisode]);

  // Sync active episode if active podcast changes
  const selectPodcast = (podcast) => {
    setActivePodcast(podcast);
    const firstEp = episodes.find((ep) => ep.podcastId === podcast.id);
    if (firstEp) {
      setActiveEpisode(firstEp);
      setCurrentTime(0);
      setIsPlaying(false);
    }
  };

  const selectEpisode = (episode) => {
    setActiveEpisode(episode);
    // Find matching podcast
    const pod = podcasts.find((p) => p.id === episode.podcastId);
    if (pod) setActivePodcast(pod);
    setCurrentTime(0);
    setIsPlaying(false);
  };

  // Skip functions
  const skipForward = (sec = 15) => {
    setCurrentTime((prev) => {
      const next = prev + sec;
      return next >= activeEpisode.durationSeconds ? activeEpisode.durationSeconds : next;
    });
  };

  const skipBackward = (sec = 15) => {
    setCurrentTime((prev) => {
      const next = prev - sec;
      return next <= 0 ? 0 : next;
    });
  };

  // Helper functions
  const formatTime = (seconds) => {
    const min = Math.floor(seconds / 60);
    const sec = Math.floor(seconds % 60);
    return `${min.toString().padStart(2, "0")}:${sec.toString().padStart(2, "0")}`;
  };

  // Add Podcast action (Upload)
  const uploadPodcast = async (title, host, category, description, durationStr, thumbnail, audioFileOrUrl) => {
    const formData = new FormData();
    formData.append("title", title);
    formData.append("host", host);
    formData.append("category", category);
    formData.append("description", description);
    formData.append("duration", durationStr || "45:00");
    
    // Check if thumbnail is a File object
    if (thumbnail instanceof File) {
      formData.append("thumbnail", thumbnail);
    }
    
    // Check if audioFileOrUrl is a File object
    if (audioFileOrUrl instanceof File) {
      formData.append("file", audioFileOrUrl);
    } else {
      // Create a dummy file if no file was uploaded, to satisfy multipart form
      const dummyBlob = new Blob(["mock audio data"], { type: "audio/mp3" });
      const dummyFile = new File([dummyBlob], "podcast.mp3", { type: "audio/mp3" });
      formData.append("file", dummyFile);
    }

    try {
      showToast("Uploading podcast and starting AI analysis pipeline...");
      const res = await fetch(`${API_BASE_URL}/api/upload`, {
        method: "POST",
        body: formData
      });
      if (res.ok) {
        const data = await res.json();
        if (data.success) {
          showToast("Upload successful. AI processing running in background.");
          await fetchPodcastsAndEpisodes();
        }
      } else {
        const errData = await res.json().catch(() => ({}));
        showToast("Upload failed: " + (errData.detail || "Server error"));
      }
    } catch (err) {
      console.error("Upload failed", err);
      showToast("Upload error: " + err.message);
    }
  };

  const deletePodcast = async (id) => {
    try {
      const res = await fetch(`${API_BASE_URL}/api/podcasts/${id}`, {
        method: "DELETE"
      });
      if (res.ok) {
        const data = await res.json();
        if (data.success) {
          showToast("Podcast and associated analysis deleted.");
          await fetchPodcastsAndEpisodes();
        }
      }
    } catch (err) {
      console.error("Delete failed", err);
      showToast("Delete failed: " + err.message);
    }
  };

  const updatePodcastDetails = (podcastId, updatedData) => {
    setPodcasts((prev) =>
      prev.map((p) => (p.id === podcastId ? { ...p, ...updatedData } : p))
    );
    // Sync activePodcast if it is the one being updated
    if (activePodcast && activePodcast.id === podcastId) {
      setActivePodcast((prev) => ({ ...prev, ...updatedData }));
    }
    // Update episode references as well
    setEpisodes((prev) =>
      prev.map((e) =>
        e.podcastId === podcastId
          ? {
              ...e,
              host: updatedData.host || e.host,
              thumbnail: updatedData.thumbnail || e.thumbnail,
              duration: updatedData.duration || e.duration
            }
          : e
      )
    );
    // Sync activeEpisode if it is part of this podcast
    if (activeEpisode && activeEpisode.podcastId === podcastId) {
      setActiveEpisode((prev) => ({
        ...prev,
        host: updatedData.host || prev.host,
        thumbnail: updatedData.thumbnail || prev.thumbnail,
        duration: updatedData.duration || prev.duration
      }));
    }
  };

  // Add chat message
  const sendChatMessage = async (episodeId, content) => {
    const newMsg = {
      id: `msg-${Date.now()}`,
      role: "user",
      content,
      timestamp: formatTime(currentTime)
    };

    setChatHistory((prev) => {
      const history = prev[episodeId] || [];
      return {
        ...prev,
        [episodeId]: [...history, newMsg]
      };
    });

    try {
      const res = await fetch(`${API_BASE_URL}/api/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: content, episode_id: episodeId })
      });
      if (res.ok) {
        const data = await res.json();
        const botMsg = {
          id: data.id || `msg-${Date.now() + 1}`,
          role: "assistant",
          content: data.content,
          timestamp: data.timestamp,
          sources: data.sources || []
        };
        setChatHistory((prev) => {
          const history = prev[episodeId] || [];
          return {
            ...prev,
            [episodeId]: [...history, botMsg]
          };
        });
      }
    } catch (err) {
      console.error("Chat backend failure, utilizing mock fallback response", err);
      // Fallback local mock if backend has issues
      const botMsg = {
        id: `msg-${Date.now() + 1}`,
        role: "assistant",
        content: "Sorry, I had trouble communicating with the PodcastMind AI backend server. Please check that it is running on port 8000.",
        timestamp: formatTime(currentTime),
        sources: []
      };
      setChatHistory((prev) => {
        const history = prev[episodeId] || [];
        return { ...prev, [episodeId]: [...history, botMsg] };
      });
    }
  };

  // AI Host Twin message sender
  const sendHostTwinMessage = async (content) => {
    const newMsg = {
      id: `ath-${Date.now()}`,
      role: "user",
      content,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setAiHostTwinHistory((prev) => [...prev, newMsg]);

    try {
      const formData = new FormData();
      formData.append("message", content);
      formData.append("personality", twinPersonality);
      formData.append("episode_id", activeEpisode.id);

      const res = await fetch(`${API_BASE_URL}/api/digital-twin/chat`, {
        method: "POST",
        body: formData
      });
      if (res.ok) {
        const data = await res.json();
        const botMsg = {
          id: `ath-${Date.now() + 1}`,
          role: "assistant",
          content: data.content,
          timestamp: data.timestamp,
          sources: data.sources || []
        };
        setAiHostTwinHistory((prev) => [...prev, botMsg]);

        if (twinVoiceMode) {
          speakHostTwinText(data.content, twinPersonality, () => setIsHostSpeaking(true), () => setIsHostSpeaking(false));
        }
      }
    } catch (err) {
      console.error("Twin chat failed", err);
      const botMsg = {
        id: `ath-${Date.now() + 1}`,
        role: "assistant",
        content: "I'm having trouble connecting to my digital twin backend brain. Make sure the FastAPI backend is running.",
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };
      setAiHostTwinHistory((prev) => [...prev, botMsg]);
    }
  };

  return (
    <PodcastContext.Provider
      value={{
        // DB
        podcasts,
        episodes,
        viralClips,
        emotionTimelines,
        knowledgeData,
        setKnowledgeData,
        audienceInsights,
        perspectives,

        // Actives
        activePodcast,
        activeEpisode,
        activePage,
        setActivePage,
        selectPodcast,
        selectEpisode,

        // Audio state
        isPlaying,
        setIsPlaying,
        currentTime,
        setCurrentTime,
        playbackSpeed,
        setPlaybackSpeed,
        volume,
        setVolume,
        skipForward,
        skipBackward,
        formatTime,
        
        // Skip & Swap logs
        skipEvents,
        setSkipEvents,
        podcastSwaps,
        setPodcastSwaps,
        getInterpolatedEmotion,

        // Actions
        uploadPodcast,
        deletePodcast,
        searchQuery,
        setSearchQuery,

        // Chat
        chatHistory,
        sendChatMessage,
        aiHostTwinHistory,
        sendHostTwinMessage,
        compareModes,
        setCompareModes,
        getEpisodeTopics,
        getTimestampExplanation,

        // Host settings
        twinPersonality,
        setTwinPersonality,
        twinVoiceMode,
        setTwinVoiceMode,
        isHostSpeaking,
        setIsHostSpeaking,

        // Global UI / Modals / Toast / Role / Integrations
        isUpgradeModalOpen,
        setIsUpgradeModalOpen,
        isApiConfigModalOpen,
        setIsApiConfigModalOpen,
        toast,
        showToast,
        userRole,
        setUserRole,
        avatar,
        setAvatar,
        isSidebarOpen,
        setIsSidebarOpen,
        apiConfig,
        setApiConfig,
        updatePodcastDetails,

        // Vector DB exports
        vectorDbSettings,
        setVectorDbSettings,
        vectorDbStats,
        isVectorIndexing,
        rebuildVectorIndex,
        vectorStoreRef
      }}
    >
      {children}
    </PodcastContext.Provider>
  );
};

export const usePodcast = () => useContext(PodcastContext);
